server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localdocker:8761/eureka/}
  instance:
    hostname: ${CONFIGURATION_SERVICE_URL:localhost}
    leaseRenewalIntervalInSeconds: 5



