server:
  port: 8888

eureka:
  client:
    region: us-east-1
    serviceUrl:
      us-east-1a: http://localhost:8761/eureka/, http://localhost2:8762/eureka/
      us-east-1b: http://localhost3:8763/eureka/
  instance:
    hostname: ${CONFIGURATION_SERVICE_URL:localhost}
    leaseRenewalIntervalInSeconds: 5



